### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by melounek** [sindresorhus/escape-goat#19]
I am running on Typescript and after updating to version `4.0.0` it started throwing this error: (`3.0.0` works fine)

<img width="857" alt="Screenshot 2021-04-28 at 14 32 42" src="https://user-images.githubusercontent.com/598369/116404762-3faa8080-a82f-11eb-94ac-dfb6da6fa37f.png">

@sindresorhus any idea what could be behind it?

**Comment by sindresorhus** [comment]
Please read the release notes.

**Comment by melounek** [comment]
I read them, but I didn't find what's wrong. I can't even use `require` in TS so if you pointing on this I am importing the module as `import { htmlUnescape } from "escape-goat";`. My node version is `15.7.0` if you are pointing on that. So I don't think not reading the release notes is the issue there.
