### ISSUE TITLE
Don't do this

### ISSUE THREAD

**Issue by meglio** [sindresorhus/escape-goat#20]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/282177/130807269-2ce3428b-0907-4b8e-8580-d4bee0c3f6e9.png">

Read more: https://www.npmjs.com/package/html-escaper

**Comment by fregante** [comment]
Not affected: https://runkit.com/fregante/61271a6c2af4f5001490ab93

```js
const {htmlUnescape} = require("escape-goat@3.0.0");

console.log(
// guess what we have here ?
htmlUnescape('&amp;lt;'),
// now guess this XSS too ...
htmlUnescape('&amp;lt;script&amp;gt;alert("yo")&amp;lt;/script&amp;gt;')
)
```


It matches the _expected_ example exactly:


<img width="679" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/130901343-40b2e1cf-3094-432f-a6fc-3404d0c9e3f1.png">

**Comment by fregante** [comment]
- Fixed 4 years ago: https://github.com/sindresorhus/escape-goat/pull/9

**Comment by meglio** [comment]
Is not relying on order error prone?
If you still want to replace non-simultaneously, may I suggest you at least add an explanatory comment to your code that says something like:

```
The order of replacements is important, do not change!
Read more: https://github.com/sindresorhus/escape-goat/pull/9
```

**Comment by fregante** [comment]
A comment explaining why would be ok, but there's already a test that guards against the change of the order. The only thing that matters is that the `&`/`&amp;` replacement happens first/last respectively.
