### ISSUE TITLE
Support unescaping all HTML escape codes.

### ISSUE THREAD

**Issue by EtherTyper** [sindresorhus/escape-goat#3]
Supporting decimal, hex, and all [character entities](https://dev.w3.org/html5/html-author/charref) would be very useful.

**Comment by ajhsu** [comment]
@EtherTyper While [mathiasbynens/he](https://github.com/mathiasbynens/he) does the same thing but supporting more features than escape-goat, I think it would be better to keep this utility library extremely simple and light, maybe?

**Comment by sindresorhus** [comment]
Yes, `he` is what you want.
