### ISSUE TITLE
Handling non-string values

### ISSUE THREAD

**Issue by ramlmn** [sindresorhus/escape-goat#7]
Maybe you should handle non-string values passed to `escape` and `unescape` methods like:
```js
// booleans
escapeGoat.escape(true);
escapeGoat.unescape(true);

// objects
escapeGoat.escape({hello: 'world'});
escapeGoat.unescape({hello: 'world'});

// other
escapeGoat.escape(null);
escapeGoat.escape(undefined);

// Any other non-string value like arrays, sets, maps, symbols, regexes
```

The origin of this issue is from [`linkify-urls`](https://github.com/sindresorhus/linkify-urls) package (dependent of escape-goat) where the following code would throw an error:
```js
const linkifyUrls = require('linkify-urls');

linkifyUrls('See https://sindresorhus.com', {
  attributes: {
    class: 'unicorn',
    hidden: true // <- this thing
  }
});

// throws
// TypeError: input.replace is not a function
```

Some type checking would be helpful with either
* converting all primitive values (boolean, null, undefined) to strings
* or returning empty string for `null` and `undefined` and only converting boolean values to strings

**Comment by sindresorhus** [comment]
It's better to fix this in `linkify-urls`.

**Comment by ramlmn** [comment]
Ok, I would like to help 😇...

**Comment by sindresorhus** [comment]
It's already fixed. See the above reference.

**Comment by ramlmn** [comment]
😇 Oh, my mistake... Sorry.
